// KAPITEL 3 – Am hohen Berg: Strickleiter und ängstliche Zwerge
export default {
  name: 'Der hohe Berg',
  musik: 'reise',
  leben: { schnee: true },
  karte: [
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'M""""""""""""""":""""""""""""""M',
    'M""""""""""""""":""""""""""""""M',
    'M"""^""""""""""":"""""""^""""""M',
    'M""""""""""""""":""""""""""""""M',
    'M"""""""""""b""":""""""""""""""M',
    'M""""""""""""""":"""c""""""""""M',
    'M""""""""^"""""":""""""""""^"""M',
    'M""""""""""""""":""""""""""""""M',
    'M""""""""""""""":""""""""""""""M',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'M..............a:......,.......M',
    'M...............:.........T....M',
    'M.....^...T.....:.......,......M',
    'M...............:.......^......M',
    'M...T...........:..............M',
    'M...............:..............M',
    'M...,/:::::::::::............,.M',
    'M..,............:....T.........M',
    'M...............:.........,.^..M',
    'M..^....,.......@..,.......,...M',
    'M...............:.............,M',
    'MMMMMMMMMMMMMMMM1MMMMMMMMMMMMMMM',
  ],
  ausgaenge: {
    1: { karte: 'wald', ziel: 2, aussehen: 'weg' },
  },
  figuren: {
    a: {
      name: 'Felswand',
      baustelle: { zu: '[', baue: [[[16, 10], [16, 11]]] },
      sprecher: 'held',
      wunsch: 'seil',
      anzahl: 1,
      sagt: 'Die Felswand ist zu steil. Mit einem Seil aus der Kiste baue ich eine Strickleiter!',
      danke: 'Eine Strickleiter! Jetzt kann ich hinaufklettern.',
    },
    b: {
      name: 'Angsthase Knut',
      aussehen: 'angsthase',
      stimme: { hoehe: 0.95, tempo: 1.1 },
      wunsch: 'mut',
      sagt: 'Oh nein, oh nein! Ich wollte zum Drachen, aber ich habe solche Angst!',
      danke: 'Du hast recht: Mutig ist, wer trotz Angst weitergeht. Danke, Grosser Zwerg!',
      danach: 'Ich glaube an dich!',
    },
    c: {
      name: 'Zitterbart Olaf',
      aussehen: 'zitterbart',
      stimme: { hoehe: 0.7 },
      wunsch: 'mut',
      sagt: 'Brrr! Da oben ist eine Höhle. Es riecht nach Feuer! Ich kehre um!',
      danke: 'Du willst trotzdem hinauf? Du bist wirklich tapfer! Hier, nimm meine Fackel mit.',
      geschenk: 'fackel',
      geschenkText: 'In der Höhle ist es dunkel. Die Fackel hilft dir.',
      danach: 'Viel Glück da oben!',
    },
  },
};
