// KAPITEL 2 – Der Burghof vor dem Schloss der Königin
export default {
  name: 'Der Burghof',
  musik: 'schloss',
  leben: { falter: 4, voegel: true, huehner: [[26, 10], [28, 11]] },
  karte: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWGWWWWGWWWWWW1WWWWWWGWWWWGWWW',
    'W>+...........L:::L..........>+W',
    'W++..........w.:::.v.........++W',
    'W.........,....:::.......T.....W',
    'W......,T......:::...,....,....W',
    'W.,............:::.,..U++......W',
    'W..ZZZ.ZZZZ...!:::!...+++....,.W',
    'W..,,,,,,,,,...:::...........K.W',
    'W..*,,,,,,,,...:::...b.......K.W',
    'W..,,B,,,,,,...:::.....p...&...W',
    'W..,,,,,,a,,...:::.........N...W',
    'W..,,,,,,,,*..!:::!.JJJJJ.JJJJ.W',
    'W..Ä..Ë..Ï.....:::.............W',
    'W...,:::::::::::::::::::::::,..W',
    'W....:::::::::::::::::::::::...W',
    'W..$.:::::::::::::::::::::::...W',
    'W..K...........:@:.............W',
    'W.......*......:::......*...,..W',
    'W..............,,..............W',
    'WWWWWGWWWWGWWWWWWWWWWGWWWWGWWWWW',
  ],
  ausgaenge: {
    1: { karte: 'thronsaal', ziel: 1 },
  },
  figuren: {
    a: {
      name: 'Gärtnerin Rosalind',
      aussehen: 'gaertnerin',
      stimme: { hoehe: 1.2 },
      // Farben sortieren: sie wünscht sich die Blumen der Reihe nach.
      // selberSuchen = der Pfeil zeigt das richtige Beet erst, wenn man die falsche Farbe bringt
      wuensche: [
        { wunsch: 'blume_rot', selberSuchen: true, sagt: 'Ich binde einen Blumenstrauss für die Königin! Bringst du mir eine ROTE Blume? Dort vorne wachsen rote, gelbe und blaue.', falsch: 'Oh, die ist auch schön! Aber ich brauche eine ROTE. Rot wie eine Erdbeere!', danke: 'Rot wie eine Erdbeere! Danke!' },
        { wunsch: 'blume_gelb', selberSuchen: true, sagt: 'Jetzt brauche ich eine GELBE Blume. Gelb wie die Sonne!', falsch: 'Hihi, das ist nicht gelb! Ich brauche eine GELBE. Gelb wie die Sonne!', danke: 'Gelb wie die Sonne! Wunderbar!' },
        { wunsch: 'blume_blau', selberSuchen: true, sagt: 'Und zum Schluss eine BLAUE Blume. Blau wie der Himmel!', falsch: 'Fast! Aber ich brauche eine BLAUE. Blau wie der Himmel!', danke: 'Fertig! Der schönste Strauss im ganzen Königreich! Danke, du Guter!' },
      ],
      danach: 'Die Königin wird sich so über den Strauss freuen.',
    },
    b: {
      name: 'Stalljunge Emil',
      aussehen: 'stalljunge',
      stimme: { hoehe: 1.7, tempo: 1.05 },
      sagt: 'Das ist Pony Flocke. Sie hat so Hunger, aber der Heuhaufen ist zu schwer für mich.',
    },
    p: {
      name: 'Pony Flocke',
      aussehen: 'pony',
      stimme: { hoehe: 1.5 },
      wunsch: 'heu',
      sagt: 'Iiihaa! Hmmm? (Flocke schaut hungrig zum Heuhaufen.)',
      danke: 'Iiihaa! Mampf, mampf. (Flocke stupst dich glücklich an.)',
      danach: 'Iiihaa! (Flocke wiehert fröhlich.)',
    },
    w: {
      name: 'Wache Borin',
      aussehen: 'wache',
      stimme: { hoehe: 0.7 },
      sagt: 'Halt! Ah, du bist der Grosse Zwerg! Die Königin erwartet dich im Thronsaal.',
    },
    v: {
      name: 'Wache Hedda',
      aussehen: 'wache2',
      stimme: { hoehe: 0.8 },
      sagt: 'So einen grossen Zwerg habe ich noch nie gesehen! Geh nur hinein.',
    },
  },
};
