// KAPITEL 2 – Der Burghof vor dem Schloss der Königin
export default {
  name: 'Der Burghof',
  musik: 'schloss',
  leben: { falter: 4, voegel: true, huehner: [[26, 10], [28, 11]] },
  karte: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWGWWWWGWWWWWW1WWWWWWGWWWWGWWW',
    'W>+...........L:::L..........>+W',
    'W++..........w.:::.v.........++W',
    'W.........,....:::.......T.....W',
    'W......,T......:::...,....,....W',
    'W.,............:::.,..U++......W',
    'W..ZZZ.ZZZZ...!:::!...+++....,.W',
    'W..,,,,,,,,,...:::...........K.W',
    'W..*,,,,,,,,...:::...b.......K.W',
    'W..,,B,,,,,,...:::.....p...&...W',
    'W..,,,,,,a,,...:::.........N...W',
    'W..,,,,,,,,*..!:::!.JJJJJ.JJJJ.W',
    'W..............:::.............W',
    'W...,:::::::::::::::::::::::,..W',
    'W....:::::::::::::::::::::::...W',
    'W..$.:::::::::::::::::::::::...W',
    'W..K...........:@:.............W',
    'W.......*......:::......*...,..W',
    'W..............,,..............W',
    'WWWWWGWWWWGWWWWWWWWWWGWWWWGWWWWW',
  ],
  ausgaenge: {
    1: { karte: 'thronsaal', ziel: 1 },
  },
  figuren: {
    a: {
      name: 'Gärtnerin Rosalind',
      aussehen: 'gaertnerin',
      stimme: { hoehe: 1.2 },
      wunsch: 'wasser',
      sagt: 'Oh, meine Rosen lassen die Köpfe hängen! Holst du mir Wasser vom Brunnen?',
      danke: 'Schau, wie sie wieder strahlen! Danke, du Guter!',
      danach: 'Die Königin liebt diese Rosen.',
    },
    b: {
      name: 'Stalljunge Emil',
      aussehen: 'stalljunge',
      stimme: { hoehe: 1.7, tempo: 1.05 },
      sagt: 'Das ist Pony Flocke. Sie hat so Hunger, aber der Heuhaufen ist zu schwer für mich.',
    },
    p: {
      name: 'Pony Flocke',
      aussehen: 'pony',
      stimme: { hoehe: 1.5 },
      wunsch: 'heu',
      sagt: 'Iiihaa! Hmmm? (Flocke schaut hungrig zum Heuhaufen.)',
      danke: 'Iiihaa! Mampf, mampf. (Flocke stupst dich glücklich an.)',
      danach: 'Iiihaa! (Flocke wiehert fröhlich.)',
    },
    w: {
      name: 'Wache Borin',
      aussehen: 'wache',
      stimme: { hoehe: 0.7 },
      sagt: 'Halt! Ah, du bist der Grosse Zwerg! Die Königin erwartet dich im Thronsaal.',
    },
    v: {
      name: 'Wache Hedda',
      aussehen: 'wache2',
      stimme: { hoehe: 0.8 },
      sagt: 'So einen grossen Zwerg habe ich noch nie gesehen! Geh nur hinein.',
    },
  },
};
