// KAPITEL 4 – Die Drachenhöhle: Freundschaft statt Kampf
export default {
  name: 'Die Drachenhöhle',
  musik: 'hoehle',
  dunkel: 0.95,
  heldLicht: 30,
  hintergrund: '#07040c',
  grundBoden: 'hoehle',
  karte: [
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖ};;;;;};;;;;;;;;;};;;;;}ÖÖÖ',
    'ÖÖÖ;;;;;;;;;;;;;;;;;;;;;;;;ÖÖÖ',
    'ÖÖÖ;;);;;;;;;;;;;;;;;;;;;;;ÖÖÖ',
    'ÖÖÖ;);;;;;;;;;;;;;;;;;;;];;ÖÖÖ',
    'ÖÖÖ;;;;;;;;;;;;d;;;;;;;;;;;ÖÖÖ',
    'ÖÖÖ;;;;;;;;;;;;;;;;;;;;;;;;ÖÖÖ',
    'ÖÖÖ;;;;;;;;;;;;;;;;;;;;;;;;ÖÖÖ',
    'ÖÖÖ;;;;;;;;;;;;;;;;;;;;;;;;ÖÖÖ',
    'ÖÖÖ};;;;;;;;;;;;;;;;;;;;;;}ÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;;;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;;;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;;;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ0000ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;;;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖ;;;;;;;;ÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖ;};;;;;;ÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖ;;;;;;};ÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖ;;;;;;;;ÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;;;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;@;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖ;;;;ÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖÖ1ÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖ',
  ],
  ausgaenge: {
    1: { karte: 'gipfel', ziel: 1, aussehen: 'weg' },
  },
  ereignisse: {
    beimBetreten: [
      { gib: 'fackel' },
      { sage: ['held', 'Ich sehe nur ein bisschen um mich herum. Ganz langsam gehe ich tiefer hinein …'] },
    ],
    ausloeser: [
      { fackel: false },
      { heldLicht: 14 },
      { sage: ['held', 'Huch! Ein Windstoss – meine Fackel ist ausgegangen!'] },
      { warte: 600 },
      { augen: { figur: 'd', dauer: 2600 } },
      { sage: ['held', 'Zwei grosse, leuchtende Augen … Das ist der Drache! Er holt tief Luft …'] },
      { entscheidung: { frage: 'Was tut der Grosse Zwerg?', knopf: 'Halt, halt, lieber Drache – ich will dir nichts tun!' } },
      { sage: ['held', 'Halt, halt, lieber Drache – ich will dir nichts tun!'] },
      { zeige: 'd' },
      { licht: 0.55 },
      { heldLicht: 50 },
      { musik: 'hoehle' },
      { sage: ['d', 'Warum? Warum willst du mir nichts tun? Alle wollen mich vertreiben.'] },
      { sage: ['d', 'Ich will doch gar nichts Böses. Ich will nur etwas essen, etwas trinken und in Frieden leben.'] },
      { sage: ['held', 'Das müssen wir nur der Königin sagen! Wir zwei können doch Freunde sein.'] },
      { sage: ['d', 'Freunde? Ich … ich heisse Glutherz. Aber jetzt habe ich erst einmal riesigen Hunger.'] },
    ],
  },
  figuren: {
    d: {
      name: 'Glutherz',
      aussehen: 'drache',
      stimme: { hoehe: 0.5, tempo: 0.9 },
      versteckt: true,
      licht: 110,
      wuensche: [
        { wunsch: 'pilze', sagt: 'Mein Bauch knurrt so laut! Bringst du mir leuchtende Pilze aus der Ecke dort?', danke: 'Mmmh! Die schmecken wunderbar! Danke!' },
        { wunsch: 'wasser', sagt: 'Und ich habe solchen Durst! Da drüben ist eine Quelle.', danke: 'Ahhh! So frisches Wasser! Du bist wirklich mein Freund.' },
      ],
      danach: 'Komm, Grosser Zwerg, wir fliegen zusammen!',
    },
  },
};
