// KAPITEL 5 – Der Marktplatz vor dem Schloss: das grosse Fest
export default {
  name: 'Der Marktplatz',
  musik: 'fest',
  leben: { falter: 6, voegel: true, wolken: true },
  karte: [
    'TTTTTTTTTTTTT.........TTTTTTTTTTTTTT',
    'TTTTTTTTTTTTT.........TTTTTTTTTTTTTT',
    'T.............{++++++..............T',
    'T.H++..,......+++++++.,........H++.T',
    'T.+++.....,,..+++++++..........+++.T',
    'T.............+++++++..............T',
    'T.....!::::::::::::::::::::::!.....T',
    'T,....::::::::w:::::v:::::::::.....T',
    'T.....:S+::::::::::::::::::S+:.....T',
    'T.....::::a:::::::::::::e:::::.....T',
    'T.....::::::::::::::::::::::::.....T',
    'T....,::q::::::::d::::::::::::.....T',
    'T.....:::::b::::::::::::::f:::.....T',
    'T.....::::::::::::::::::::::::.....T',
    'T.....:::c::::::::::::::::::::.....T',
    'T.....:::::::::::@:::::::g::::.....T',
    'T...,.:::::::::::::::::::::p::.....T',
    'T.....::::::h:::::::::j:::::::.....T',
    'T.....::::::::::B:::::::::::::.....T',
    'T.H++.!::::::::::::::::::::::!.H++.T',
    'T.+++.,........................+++,T',
    'T......,...........................T',
    'T..................................T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
  ausgaenge: {},
  ereignisse: {
    beimBetreten: [
      { zeige: 'd' },
      { wackeln: 500 },
      { ton: 'grollen' },
      { warte: 700 },
      { sage: ['a', 'Hilfe! Ein Drache! Mitten auf dem Marktplatz!'] },
      { sage: ['b', 'Aber schaut mal – auf seinem Rücken sitzt der Grosse Zwerg!'] },
      { sage: ['held', 'Keine Angst! Das ist mein Freund Füürio. Er tut niemandem etwas.'] },
      { sage: ['held', 'Liebe Königin, bitte kommt herunter! Wir möchten Euch einen Vorschlag machen.'] },
      { ton: 'fanfare' },
      { figurKommt: { aussehen: 'koenigin', name: 'Königin Brunhild', hoehe: 1.05, buchstabe: 'k', von: [17, 6], nach: [20, 12], dauer: 2400 } },
      { sage: ['k', 'Grosser Zwerg! Du bist zurück – und du bringst den Drachen mit?'] },
      { sage: ['d', 'Liebe Königin, ich wollte nie jemandem Angst machen. Ich wollte nur essen, trinken und in Frieden leben.'] },
      { sage: ['held', 'Wir zwei möchten das Zwergenreich beschützen – so lange wir können!'] },
      { sage: ['k', 'Was für ein wunderbarer Vorschlag! Mut, Freundschaft und ein grosses Herz – genau das braucht unser Reich.'] },
      { sage: ['k', 'Hiermit ernenne ich euch beide zu Ehrenmitgliedern der königlichen Garde!'] },
      { jubel: ['a', 'b', 'c', 'e', 'f', 'g', 'h', 'j', 'q', 'p', 'w', 'v', 'd'] },
      { splash: { titel: 'Ehrenmitglieder der Garde!', text: 'Der Grosse Zwerg und Füürio beschützen das Zwergenreich.', bild: 'held_unten_jubeln', farbe: 0xe0b23c } },
      { sage: ['d', 'Hurra! Ich habe Freunde!'] },
      { sage: ['c', 'Du bist doch der allerbeste Zwerg von allen!'] },
      { warte: 600 },
      { szene: 'Abspann' },
    ],
  },
  figuren: {
    d: { name: 'Füürio', aussehen: 'drache', zustand: 'froh', stimme: { hoehe: 0.5 }, versteckt: true, sagt: 'Ich bin so froh, dass ich jetzt Freunde habe!' },
    a: { name: 'Mama Hilde', aussehen: 'mama', stimme: { hoehe: 1.25 }, sagt: 'Mein Grosser! Ich bin so stolz auf dich!' },
    b: { name: 'Tilda', aussehen: 'tilda', stimme: { hoehe: 1.8 }, sagt: 'Darf ich auch mal auf dem Drachen reiten?' },
    c: { name: 'Bruno', aussehen: 'bruno', stimme: { hoehe: 1.6 }, sagt: 'Du bist der beste Zwerg der Welt!' },
    e: { name: 'Schmied Balin', aussehen: 'schmied', stimme: { hoehe: 0.6 }, sagt: 'Für einen Ehren-Gardisten schmiede ich einen goldenen Helm!' },
    f: { name: 'Oma Runa', aussehen: 'oma', stimme: { hoehe: 1.1 }, sagt: 'Ein grosses Herz ist mehr wert als alles Gold. Das habe ich immer gesagt.' },
    g: { name: 'Händler Dwalin', aussehen: 'haendler', stimme: { hoehe: 0.8 }, sagt: 'Heute gibt es Kuchen für alle – auch für den Drachen!' },
    h: { name: 'Bauer Gorm', aussehen: 'bauer', stimme: { hoehe: 0.75 }, sagt: 'Mit einem Drachen als Freund wird meine Ernte bestimmt noch besser.' },
    j: { name: 'Nella', aussehen: 'nella', stimme: { hoehe: 1.7 }, sagt: 'Ich hab dich lieb, Grosser Zwerg!' },
    q: { name: 'Bibliothekar Thorin', aussehen: 'bibliothekar', stimme: { hoehe: 0.7 }, sagt: 'Diese Geschichte schreibe ich in das grösste Buch der Bibliothek!' },
    p: { name: 'Pip', aussehen: 'pip', stimme: { hoehe: 1.9 }, sagt: 'Ein echter Drache! Genau wie in meinem Drachenbuch!' },
    w: { name: 'Wache Borin', aussehen: 'wache', stimme: { hoehe: 0.7 }, sagt: 'Willkommen in der Garde, Kamerad!' },
    v: { name: 'Wache Hedda', aussehen: 'wache2', stimme: { hoehe: 0.8 }, sagt: 'Mit euch zwei ist das Reich sicher.' },
  },
};
