// KAPITEL 3 – Der See: Trittsteine legen
export default {
  name: 'Der grosse See',
  musik: 'reise',
  leben: { falter: 5, voegel: true, wolken: true },
  karte: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'T.,.........~......,,............T',
    'T,.....,....~~~~~~~~.............T',
    'T,........*.~~~~~~~~..,..,.,.....T',
    'T..D.........~~~~~~~.......^.....T',
    'T.D.....,....~~~~~~~.....<.......T',
    'T.......f....~~~~~~~.............T',
    'T.........,..~~~~~~~.......,..<..T',
    'T...<........~~~~~~~.,...........T',
    'T,....,.....a~~~~~~~.........,,..T',
    'T:@::::::::::~~~~~~~:::::::::::::1',
    'T............~~~~~~~,............T',
    'T............~~~~~~~......*......T',
    'T..*...,,....~~~~~~~.....,.,.....T',
    'T,...C.......~~~~~~~........<....T',
    'T......<.....~~~~~~~.............T',
    'T...,....^...~~~~~~~..........,..T',
    'T............~~~~~~~...<.........T',
    'T........<..~~~~~~~~.......,.....T',
    'T....,......~~~~~~~~.............T',
    'T,..........~.............,......T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
  ausgaenge: {
    1: { karte: 'tal', ziel: 1, weiter: true, aussehen: 'weg' },
  },
  figuren: {
    a: {
      name: 'Trittsteine',
      baustelle: { zu: 'O', baue: [[[13, 10], [14, 10]], [[15, 10], [16, 10]], [[17, 10], [18, 10], [19, 10]]] },
      sprecher: 'held',
      wunsch: 'stein',
      anzahl: 3,
      sagt: 'Hier ist der See zu tief. Wenn ich Steine vom Steinhaufen hineinlege, kann ich darüber gehen!',
      weiter: 'Platsch! Noch {rest} Steine!',
      danke: 'Geschafft! Jetzt komme ich über den See.',
    },
    f: {
      name: 'Fischerin Marit',
      aussehen: 'fischerin',
      stimme: { hoehe: 1.15 },
      wunsch: 'beeren',
      sagt: 'Heute beisst kein Fisch an. Ich habe Hunger! Bringst du mir Beeren vom Busch?',
      danke: 'Mmmh, süss und lecker! Danke, Grosser Zwerg. Gute Reise!',
      danach: 'Pass auf, drüben im Wald wird es dunkel!',
    },
  },
};
