// KAPITEL 3 – Das tiefe Tal: eine Brücke bauen
export default {
  name: 'Das tiefe Tal',
  musik: 'reise',
  leben: { falter: 3, voegel: true, wolken: true },
  karte: [
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'M.............XXXXXX.............M',
    'M...,..,......XXXXXX.............M',
    'M.,^.,.....T,.XXXXXX..........T..M',
    'M...].........XXXXXX....^........M',
    'M.......w...,.XXXXXX..........,..M',
    'M.......^.....XXXXXX.............M',
    'M.............XXXXXX.......^.....M',
    'M........,....XXXXXX,........,...M',
    'M....,.......aXXXXXX......,......M',
    '1:::::::::::::XXXXXX:::::::::::::2',
    'M.............XXXXXX.............M',
    'M.............XXXXXX....,........M',
    'M........,...,XXXXXX.............M',
    'M.....,.......XXXXXX.............M',
    'M....`........XXXXXX..T......^...M',
    'M.....%...^...XXXXXX.............M',
    'M.T...........XXXXXX.............M',
    'M..........,..XXXXXX.....^.....T.M',
    'M.............XXXXXX...........,.M',
    'M.............XXXXXX.......,...,.M',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
  ],
  ausgaenge: {
    1: { karte: 'see', ziel: 1, aussehen: 'weg' },
    2: { karte: 'wald', ziel: 1, weiter: true, aussehen: 'weg' },
  },
  figuren: {
    a: {
      name: 'Brücke',
      baustelle: { zu: '=', baue: [[[14, 10], [15, 10]], [[16, 10], [17, 10]], [[18, 10], [19, 10]]] },
      sprecher: 'held',
      wunsch: 'brett',
      anzahl: 3,
      sagt: 'Oh, ist das tief! Mit Brettern vom Holzstapel baue ich eine Brücke.',
      weiter: 'Klong, klong! Noch {rest} Bretter!',
      danke: 'Die Brücke ist fertig! Stark und sicher.',
    },
    w: {
      name: 'Wanderer Oswin',
      aussehen: 'wanderer',
      stimme: { hoehe: 0.75, tempo: 0.9 },
      wunsch: 'wasser',
      sagt: 'Puh, ich bin so lange gewandert. Holst du mir Wasser aus der Quelle?',
      danke: 'Ahh, das tut gut! Danke. Du hast ein grosses Herz.',
      danach: 'Hinter dem dunklen Wald beginnt der hohe Berg.',
    },
  },
};
