// KAPITEL 3 – Der dunkle Wald: Glühwürmchen zeigen den Weg
export default {
  name: 'Der dunkle Wald',
  musik: 'wald',
  dunkel: 0.82,
  heldLicht: 58,
  hintergrund: '#0e140e',
  leben: { gluehwuermchen: [[5, 10], [9, 8], [12, 5], [17, 9], [21, 13], [26, 11], [29, 5]] },
  karte: [
    '<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<',
    '<......*.<.*..<<.*<*<.<.<<..<..T.<',
    '<.T<..T..*.T.T.*..<...<......T.<T<',
    '<....T<..*<*T...<..<..*.**..*..T*<',
    '<.<...T...T.....*T..<..T.........<',
    '<.......T.....*T.<..<.*.<<.....<T<',
    '<*......::::::::::.T......:::::::2',
    '<...*...:...<<*..:.....T.T:.T.**<<',
    '<..T*.T.:.*.....<:T..T...T:..<*..<',
    '<..(....:....<..*:.*......:<<..*.<',
    '<...<.T.:.<.<<,,,:,,,..<..:**...T<',
    '1::::::::T...<P,P:,,,T.<..:.<.<<.<',
    '<....<.......*,m,:P,,.*.T.:.....*<',
    '<..<..<<*...**,,,:,,P<.*..:.<..<.<',
    '<.<....T<.<...,,,::::::::::....T*<',
    '<<<....<..<...,P,,,P,.<**<...*...<',
    '<.*<T.<..<....,,,,,,,.<.*...*T.<.<',
    '<.....*.<...T..T.........*.TT.<<<<',
    '<...<*<.<.<.*.T.*<.....*.<<...T.T<',
    '<.......*.<.<..<.....<.<.<.......<',
    '<...<.....<T.....<<.......<.*.*..<',
    '<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<',
  ],
  ausgaenge: {
    1: { karte: 'tal', ziel: 2, aussehen: 'weg' },
    2: { karte: 'berg', ziel: 1, weiter: true, aussehen: 'weg' },
  },
  ereignisse: {
    beimBetreten: [
      { sage: ['held', 'Hier ist es aber dunkel … Zum Glück zeigen mir die Glühwürmchen den Weg.'] },
    ],
  },
  figuren: {
    m: {
      name: 'Waldzwergin Mira',
      aussehen: 'mira',
      stimme: { hoehe: 1.8, tempo: 1.05 },
      licht: 70,
      lichtNachErfuellt: true,
      wunsch: 'fackel',
      sagt: 'Huhu … ich habe mich verlaufen und fürchte mich im Dunkeln. Bringst du mir Licht von der Feuerschale?',
      danke: 'Oh, wie schön hell! Jetzt habe ich keine Angst mehr. Danke!',
      danach: 'Mit Licht ist der Wald gar nicht so gruselig.',
    },
  },
};
